version: '3.4'

services:
  usersapi:
    container_name: usersapi
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_CONNECTION_STRING=redis://usersdb:7000
      - EPPlus__ExcelPackage__Compatibility__IsWorksheets1Based=false
      - EPPlus__ExcelPackage__LicenseContext=NonCommercial
    depends_on:
      - usersdb
    ports:
      - "31431:80"
    networks: 
        - nxt

  usersdb:
   container_name: usersdb
   image: redis/redis-stack-server
   restart: always
   environment:
    - "REDIS_ARGS= --SAVE 10 1 --PORT 7000"
   ports:
    - "7000:7000"
   deploy:
     replicas: 1
     restart_policy:
        condition: on-failure
   volumes:
    - redisData:/data
   networks: 
        - nxt

networks:
   nxt:
    driver: bridge
    external: true
    
volumes:
  redisData:
